### ISSUE TITLE
Extra hyphens at re-add argument

### ISSUE THREAD

**Issue by levlist** [yamaton/h2o-curated-data#2]
Hi,

if you are using the completion function and select an element from the offered list, it inserts fine, but for instance, you delete the part of the inserted argument and you want to add it again by CTRL+SPACE the list appears again, and when you want to add it again it will insert extra hyphens.

![Code_1gh8FcNgZG](https://user-images.githubusercontent.com/10905822/158952037-40bc771c-e2ff-405c-9445-7151c89c8080.gif)

I experienced the same issue with other commands as well.

**Comment by yamaton** [comment]
Thank you for the clarification! 

Actually this is THE nagging issue I've always wanted to solve since the beginning. Editor setting like `Editor: Word Separators` does not help, and I suppose the issue is rooted from the shellscript language definition within VS Code.

I am planning to update the extension by implementing language server protocol, hopefully by the end of April, and the update will have a lot more controls and be able to solve this issue as well.  Please stay tuned.

**Comment by yamaton** [comment]
@levlist The latest version of [the VS Code Extension](https://marketplace.visualstudio.com/items?itemName=tetradresearch.vscode-h2o) (v0.2.5) fixed the issue. Sorry that it took this long, but I finally made it.

**Comment by levlist** [comment]
Thank you!
